In [1]:
import numpy as np
import tensorflow as tf
from keras import models, layers, optimizers
from tensorflow.keras.losses import CategoricalCrossentropy
# from keras_tuner import HyperParameters, RandomSearch

# data manipulation
from keras.utils import to_categorical
from imblearn.over_sampling import RandomOverSampler, SMOTE
from imblearn.under_sampling import RandomUnderSampler

# data processing
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import pandas as pd
import csv

# plotting
import matplotlib.pyplot as plt
import seaborn as sns

import os
for dirname, _, filenames in os.walk('backend/data'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

ModuleNotFoundError: No module named 'tensorflow'

### Processing Data

In [14]:
# def stringToCategorical

In [15]:
data = pd.read_csv(r'data\Disease_symptom_and_patient_profile_dataset.csv')
print(data.head())

# # # one hot encoding
data['Gender'] = LabelEncoder().fit_transform(data['Gender'])
data['Blood Pressure'] = LabelEncoder().fit_transform(data['Blood Pressure'])
data['Cholesterol Level'] = LabelEncoder().fit_transform(data['Cholesterol Level'])
data['Fever'] = LabelEncoder().fit_transform(data['Fever'])
data['Fatigue'] = LabelEncoder().fit_transform(data['Fatigue'])
data['Cough'] = LabelEncoder().fit_transform(data['Cough'])
data['Difficulty Breathing'] = LabelEncoder().fit_transform(data['Difficulty Breathing'])

y = pd.Categorical(data["Disease"])
y = pd.get_dummies(y)
y_labels = sorted(list(set(y)))

X = np.array(data.drop(["Disease", "Outcome Variable"], axis=1)) # axis 1 is whole columns

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

       Disease Fever Cough Fatigue Difficulty Breathing  Age  Gender  \
0    Influenza   Yes    No     Yes                  Yes   19  Female   
1  Common Cold    No   Yes     Yes                   No   25  Female   
2       Eczema    No   Yes     Yes                   No   25  Female   
3       Asthma   Yes   Yes      No                  Yes   25    Male   
4       Asthma   Yes   Yes      No                  Yes   25    Male   

  Blood Pressure Cholesterol Level Outcome Variable  
0            Low            Normal         Positive  
1         Normal            Normal         Negative  
2         Normal            Normal         Negative  
3         Normal            Normal         Positive  
4         Normal            Normal         Positive  


In [16]:
print(y)

      Acne  Allergic Rhinitis  Alzheimer's Disease  Anemia  Anxiety Disorders  \
0    False              False                False   False              False   
1    False              False                False   False              False   
2    False              False                False   False              False   
3    False              False                False   False              False   
4    False              False                False   False              False   
..     ...                ...                  ...     ...                ...   
344  False              False                False   False              False   
345  False              False                False   False              False   
346  False              False                False   False              False   
347  False              False                False   False              False   
348  False              False                False   False              False   

     Appendicitis  Asthma  

In [17]:
print(X)

[[1 0 1 ... 0 1 2]
 [0 1 1 ... 0 2 2]
 [0 1 1 ... 0 2 2]
 ...
 [1 0 1 ... 1 0 0]
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]]


### Apply Neural Network

In [18]:
model = models.Sequential([
    layers.Dense(units = 16,input_dim = len(X_train[0]), activation = 'relu'),
    layers.Dense(units = 8, activation = 'sigmoid'),
    layers.Dense(units = len(y_labels), activation = 'softmax')
])

#loss
model.compile(optimizer = optimizers.Adam(learning_rate=1e-3), loss = CategoricalCrossentropy(),metrics=['accuracy']) #

# early_stopping = EarlyStopping(monitor='recall', patience=4,restore_best_weights=True)

#fit
model.fit(X_train,y_train,epochs = 40, batch_size=4)

Epoch 1/40
79/79 [==============================] - 1s 1ms/step - loss: 4.7657 - accuracy: 0.0096
Epoch 2/40
79/79 [==============================] - 0s 1ms/step - loss: 4.6759 - accuracy: 0.0255
Epoch 3/40
79/79 [==============================] - 0s 2ms/step - loss: 4.5372 - accuracy: 0.0446
Epoch 4/40
79/79 [==============================] - 0s 1ms/step - loss: 4.4186 - accuracy: 0.0446
Epoch 5/40
79/79 [==============================] - 0s 1ms/step - loss: 4.3559 - accuracy: 0.0701
Epoch 6/40
79/79 [==============================] - 0s 1ms/step - loss: 4.3207 - accuracy: 0.0701
Epoch 7/40
79/79 [==============================] - 0s 1ms/step - loss: 4.3030 - accuracy: 0.0701
Epoch 8/40
79/79 [==============================] - 0s 1ms/step - loss: 4.2908 - accuracy: 0.0701
Epoch 9/40
79/79 [==============================] - 0s 2ms/step - loss: 4.2807 - accuracy: 0.0701
Epoch 10/40
79/79 [==============================] - 0s 1ms/step - loss: 4.2690 - accuracy: 0.0701
Epoch 11/40
79/79 [

In [19]:
test_results = model.evaluate(X_test, y_test, return_dict=True, verbose=0)
test_acc = test_results['accuracy']
print("Test Accuracy:",test_acc)

Test Accuracy: 0.05714285746216774
